svenjacobs/leon

CHANGELOG.md, app/build.gradle.kts, app/src/main/java/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/java/com/svenjacobs/app/leon/ui/screens/main/model/MainViewModel.kt, app/src/main/play/release-notes/de-DE/default.txt, app/src/main/play/release-notes/en-US/default.txt
* :bug: Fix back nav icon not visible in preferences
* :memo: Update CHANGELOG
=> Release 0.4.1

app/src/main/java/com/svenjacobs/app/leon/domain/Defaults.kt, app/src/main/java/com/svenjacobs/app/leon/domain/model/Sanitizer.kt
:sparkles: Add fbclid parameter to Facebook sanitizer
=> Add fbclid parameter to Facebook sanitizer

app/build.gradle.kts, app/src/main/java/com/svenjacobs/app/leon/domain/Defaults.kt, app/src/main/java/com/svenjacobs/app/leon/domain/model/Sanitizer.kt, app/src/main/java/com/svenjacobs/app/leon/repository/db/Converters.kt, app/src/main/java/com/svenjacobs/app/leon/repository/db/mapper/DbSanitizerMapper.kt, app/src/main/java/com/svenjacobs/app/leon/repository/db/model/DbSanitizer.kt, app/src/main/java/com/svenjacobs/app/leon/services/SanitizerStrategy.kt, app/src/main/java/com/svenjacobs/app/leon/startup/Migrations.kt, app/src/main/java/com/svenjacobs/app/leon/ui/screens/home/BroomIcon.kt, app/src/main/java/com/svenjacobs/app/leon/ui/screens/home/HomeScreen.kt, app/src/main/java/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/java/com/svenjacobs/app/leon/ui/screens/main/model/Screen.kt, app/src/main/res/values-de/a11y.xml, app/src/main/res/values/a11y.xml, app/src/test/java/com/svenjacobs/app/leon/service/CleanerServiceTest.kt
=> Release 0.5.0

app/build.gradle.kts, feature-sanitizer-youtube/build.gradle.kts, feature-sanitizer-youtube/src/main/AndroidManifest.xml, feature-sanitizer-youtube/src/main/kotlin/com/svenjacobs/app/leon/feature/sanitizer/youtube/YoutubeModule.kt, feature-sanitizer-youtube/src/main/kotlin/com/svenjacobs/app/leon/feature/sanitizer/youtube/YoutubeRedirectSanitizer.kt, feature-sanitizer-youtube/src/main/kotlin/com/svenjacobs/app/leon/feature/sanitizer/youtube/YoutubeRedirectSanitizerRegistration.kt, feature-sanitizer-youtube/src/main/res/values-de/strings.xml, feature-sanitizer-youtube/src/main/res/values/strings.xml, feature-sanitizer-youtube/src/test/kotlin/com/svenjacobs/app/leon/feature/sanitizer/amazon/YoutubeRedirectSanitizerTest.kt
=> feat: Add YouTube redirect sanitizer

feature-sanitizer-youtube/src/main/kotlin/com/svenjacobs/app/leon/feature/sanitizer/youtube/YoutubeShortUrlSanitizer.kt, feature-sanitizer-youtube/src/main/kotlin/com/svenjacobs/app/leon/feature/sanitizer/youtube/YoutubeShortUrlSanitizerRegistration.kt, feature-sanitizer-youtube/src/main/res/values/strings.xml, feature-sanitizer-youtube/src/test/kotlin/com/svenjacobs/app/leon/feature/sanitizer/amazon/YoutubeShortUrlSanitizerTest.kt
=> feat: Add youtu.be short URL sanitizer

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/svenjacobs/app/leon/MainActivity.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/model/SettingsScreenViewModel.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
=> feat: Register Léon as browser

CONTRIBUTING.md, app/src/main/kotlin/com/svenjacobs/app/leon/datastore/AppDataStoreManager.kt, app/src/main/kotlin/com/svenjacobs/app/leon/datastore/SanitizerDataStoreManager.kt, app/src/main/kotlin/com/svenjacobs/app/leon/startup/Migrations.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/CleanerService.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/Sanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/SanitizerRegistration.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/SanitizerRepository.kt
- chore: Add CONTRIBUTING.md
- chore: Add more code documentation
Closes #32
=> Add CONTRIBUTING.md & update documentation

CHANGELOG.md, app/build.gradle.kts, app/src/main/kotlin/com/svenjacobs/app/leon/startup/ComponentInitializer.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/model/SettingsSanitizersScreenViewModel.kt, app/src/main/play/release-notes/de-DE/default.txt, app/src/main/play/release-notes/en-US/default.txt, feature-sanitizer-ebay/build.gradle.kts, feature-sanitizer-ebay/src/main/AndroidManifest.xml, feature-sanitizer-ebay/src/main/kotlin/com/svenjacobs/app/leon/feature/sanitizer/ebay/EbaySanitizer.kt, feature-sanitizer-ebay/src/main/kotlin/com/svenjacobs/app/leon/feature/sanitizer/ebay/EbaySanitizerRegistration.kt, feature-sanitizer-ebay/src/main/res/values/strings.xml, feature-sanitizer-ebay/src/test/kotlin/com/svenjacobs/app/leon/feature/sanitizer/amazon/EbaySanitizerTest.kt
=> feat: Add eBay sanitizer

app/build.gradle.kts, buildSrc/src/main/kotlin/android-library.gradle.kts, gradle/libs.versions.toml
Update dependencies and use new [Compose BOM](https://developer.android.com/jetpack/compose/setup#using-the-bom).
=> chore: Update dependencies

.github/workflows/build.yml, .github/workflows/deploy.yml, app/build.gradle.kts
=> chore: Automatically increment version code

CHANGELOG.md, app/build.gradle.kts
=> fix: Fix build issue on F-Droid

.github/workflows/build.yml, .github/workflows/deploy.yml
=> feat: Automatically create GitHub releases

.github/workflows/build.yml, app/build.gradle.kts
=> fix: Remove git-secret from build.yml workflow

app/src/main/kotlin/com/svenjacobs/app/leon/sanitizer/aliexpress/AliexpressSanitizer.kt, app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, app/src/main/res/values/strings.xml, app/src/test/kotlin/com/svenjacobs/app/leon/sanitizer/aliexpress/AliexpressSanitizerTest.kt
Copy paste from the EbaySanitizer, first version to figure out the inner workings
Closes #91
=> Add Aliexpress sanitizer

app/src/main/kotlin/com/svenjacobs/app/leon/sanitizer/linksynergy/LinkSynergySanitizer.kt, app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, app/src/main/res/values/strings.xml, app/src/test/kotlin/com/svenjacobs/app/leon/sanitizer/linksynergy/LinkSynergySanitizerTest.kt
Hi,
I thought I'd try and address some of the low hanging open pull requests, so this pull request adds support for LinkSynergy links. It doesn't _fully_ address #84 as the recursive behaviour is not implemented - that's a bit beyond me at the moment.
I've not updated the `CHANGELOG.md` as I don't know how you handle your releases, but I can do if you'd like.
Thanks,
Ari
Closes #84
=> Support LinkSynergy links, fix #84

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-common/src/main/kotlin/com/svenjacobs/app/leon/core/common/regex/RegexFactory.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/georiot/GeoRiotSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/google/GoogleAdsSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/google/GoogleSearchSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/linksynergy/LinkSynergySanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeRedirectSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/google/GoogleAdsSanitizerTest.kt
- fix: Remove unnecessary regex capturing group
- feat: Add Google Ads sanitizer
- chore: Use RegexFactory where appropriate
Fixes #133
=> feat: Add Google Ads sanitizer

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeMusicSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeMusicSanitizerTest.kt
=> feat: Add YouTube Music sanitizer

app/src/main/res/values-pl/a11y.xml, app/src/main/res/values-pl/strings.xml
=> chore: Add Polish translation (by @rehork)

.idea/codeStyles/Project.xml, app/build.gradle.kts, app/src/main/kotlin/com/svenjacobs/app/leon/MainActivity.kt, app/src/main/kotlin/com/svenjacobs/app/leon/datastore/AppDataStoreManager.kt, app/src/main/kotlin/com/svenjacobs/app/leon/datastore/SanitizerDataStoreManager.kt, app/src/main/kotlin/com/svenjacobs/app/leon/inject/AppContainer.kt, app/src/main/kotlin/com/svenjacobs/app/leon/sanitizer/SanitizerRepositoryImpl.kt, app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/MainRouter.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/model/MainScreenViewModel.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsSanitizersScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/model/SettingsSanitizersScreenViewModel.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/model/SettingsScreenViewModel.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml, buildSrc/src/main/kotlin/android-library.gradle.kts, buildSrc/src/main/kotlin/kotlin-library.gradle.kts, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/CleanerService.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/action/ActionAfterClean.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/inject/DomainContainer.kt, gradle/libs.versions.toml
This PR adds a new "action after clean" setting with three possible values:
* Do nothing
* Open share menu
* Copy to clipboard
Closes #169
Closes #71
=> feat: Add action after clean setting (open share menu, copy to clipboard)

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/lazada/LazadaSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/lazada/LazadaSanitizerTest.kt
=> feat: Add Lazada sanitizer

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/shopee/ShopeeSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/shopee/ShopeeSanitizerTest.kt
=> feat: Add Shopee sanitizer

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, buildSrc/src/main/kotlin/kotlin-library.gradle.kts, core-common/src/main/kotlin/com/svenjacobs/app/leon/core/common/domain/DomainExtensions.kt, core-common/src/test/kotlin/com/svenjacobs/app/leon/core/common/domain/DomainExtensionsTest.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/aliexpress/AliexpressSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/aol/AolSearchSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/change/ChangeSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/ebay/EbaySanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/elfinanciero/ElFinancieroSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/flipkart/FlipkartSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/georiot/GeoRiotSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/google/GoogleAdsSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/google/GoogleSearchSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/instagram/InstagramSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/jdoqocy/JdoqocySanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/lazada/LazadaSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/linksynergy/LinkSynergySanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/netflix/NetflixSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/newegg/NewEggSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/pearl/PearlSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/shopee/ShopeeSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/spiegel/SpiegelSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/spotify/SpotifySanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/twitter/TwitterSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/yahoo/YahooSearchSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeRedirectSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/pearl/PearlSanitizerTest.kt
=> feat: Add pearl.de sanitizer

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/theguardian/TheGuardianSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/theguardian/TheGuardianSanitizerTest.kt
=> feat: Add sanitizer for The Guardian

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizerTest.kt
=> feat: Improve Amazon product sanitizer

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/twitter/TwitterSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/twitter/TwitterSanitizerTest.kt
=> fix: Remove all parameters from Twitter URLs

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-common/src/main/kotlin/com/svenjacobs/app/leon/core/common/url/DecodeUrl.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/CleanerService.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/reddit/RedditMailSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/reddit/RedditOutSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/reddit/RedditMailSanitizerTest.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/reddit/RedditOutSanitizerTest.kt
=> feat: Add Reddit sanitizers

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizerTest.kt
=> feat: Add YouTube sanitizer

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/spotify/SpotifySanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/spotify/SpotifySanitizerTest.kt
=> fix: Spotify sanitizer

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/threads/ThreadsSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/threads/ThreadsSanitizerTest.kt
=> feat: Add Threads.net sanitizer

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/netflix/NetflixSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/netflix/NetflixSanitizerTest.kt
=> fix: Fix Netflix sanitizer for help.netflix.com domain

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/facebook/FacebookAnalyticsSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/facebook/FacebookAnalyticsSanitizerTest.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/facebook/FacebookSanitizerTest.kt
=> feat: Add sanitizer for facebook.com

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/at/AtAnalyticsSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/at/AtAnalyticsSanitizerTest.kt
=> feat: Add sanitizer for AT Analytics

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizerTest.kt
=> fix: YouTube sanitizer for search results

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/reddit/RedditSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/reddit/RedditSanitizerTest.kt
=> feat: Add sanitizer for Reddit

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizerTest.kt
=> fix: Amazon sanitizer for gp/product links

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/model/MainScreenViewModel.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/model/Screen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/theme/Colors.kt, app/src/main/res/values-de/a11y.xml, app/src/main/res/values-pl/a11y.xml, app/src/main/res/values-ru/a11y.xml, app/src/main/res/values/a11y.xml, buildSrc/src/main/kotlin/Android.kt
- chore: Raise targetSdk to 34 (Android 14)
- chore: Fix some warnings
=> chore: Raise targetSdk to 34 (Android 14)

app/src/main/kotlin/com/svenjacobs/app/leon/MainActivity.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsLicensesScreen.kt, build.gradle.kts, gradle/libs.versions.toml
=> fix: Material 3 dynamic colors & dark mode in some screens

.all-contributorsrc, README.md
Updated manually because of merge conflicts
=> chore: Update contributors

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/fastcompany/FastCompanySanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/fastcompany/FastCompanySanitizerTest.kt
=> feat: Add sanitizer for fastcompany.com

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/netflix/NetflixSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/netflix/NetflixSanitizerTest.kt
=> fix: Add trg parameter to Netflix sanitizer

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/aliexpress/AliexpressSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/aliexpress/AliexpressSanitizerTest.kt
=> fix: AliExpress sanitizer for subdomains

app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/yandex/YandexSanitizer.kt, core-domain/src/main/res/values/strings.xml, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/yandex/YandexSanitizerTest.kt
=> feat: Add Yandex sanitizer

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/SearchResultSanitizer.kt, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/yahoo/YahooSearchSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/yahoo/YahooSearchSanitizerTest.kt
=> fix: Yahoo sanitizer for search query links

.github/CODEOWNERS, .github/dependabot.yml
- chore: Update Dependabot config
- chore: Add CODEOWNERS
=> chore: Update Dependabot config

app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsScreen.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml, core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/action/ActionAfterClean.kt
=> feat: Add "Open URL" action after clean

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/instagram/InstagramSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/instagram/InstagramSanitizerTest.kt
Should fix #336 
Change tracking parameter of Instagram from `igshid` to `igsh`.
=> Fix Instagram (igshid -> igsh)

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizerTest.kt
=> fix: YT sanitizer for playlist URLs

app/build.gradle.kts, app/src/main/res/resources.properties
https://developer.android.com/guide/topics/resources/app-languages
=> feat: Add support for per-app language preferences

app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt
=> feat: Make original & cleaned URL selectable

app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
=> feat: show message when clipboard is empty

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/svenjacobs/app/leon/ProcessTextActivity.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
Closes #386
https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999
=> feat: provide text selection action

API.md, README.md, app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/svenjacobs/app/leon/MainActivity.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ProcessTextActivity.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/views/BottomBar.kt
=> feat: add API for programmatic usage

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizerTest.kt
=> Keep time mark parameter for YouTube URLs

app/src/main/kotlin/com/svenjacobs/app/leon/ui/common/Browser.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt, app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsScreen.kt
=> fix: lock open button if Leon is default browser

core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizer.kt, core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizerTest.kt
=> fix: YouTube sanitizer should also clean youtu.be domain
